### ISSUE TITLE
💔 Running `yarn start` produces an error at runtime inside Figma

### ISSUE THREAD

**Issue by sergeen** [YumYumNyang/yummy-figma-plugin#1]
First of all: I love this plug-in, great work! ❤️ 

Second: I'm forking it to make my version, and I'm running into an issue...

When I run `yarn build` everything works okay. But if I run `yarn start` I get this error at runtime inside the Figma console:

<pre>
figma_app.min.js.br:5 Syntax error on line 372: <b>Unexpected reserved word</b>
            if (asset.outputFormat === "esmodule") return import(asset.url + "?t=" + Date.now());
</pre>

I started to work on the issue by creating a custom `.parcelrc` file with this configuration:

<pre>
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "*.js": ["@parcel/transformer-babel"]
    }
}
</pre>

But it now causes another error at compile time:

<pre>
VM716:728 Uncaught SyntaxError: Cannot use import statement outside a module[...]
</pre>

and it breaks at compile time when I run `yarn build` 😞 

<pre>
🚨 Build failed.

@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')
</pre>

I can of course remove my configuration and run `yarn build` but I would prefer a keep the normal workflow of using `yarn start` for development.

**Comment by YumYumNyang** [comment]
thank you for letting me know this issue, and sorry that I checked this too late.
I will try to find why it's not working asap!!

**Comment by YumYumNyang** [comment]
@sergeen  Hi, I checked this issue
and I found that this issue happens because parcel hmr inserts es6+ code (syntaxes like import, async..)  
so I just add option '--no-hmr' when 'yarn start' script starts.
