### ISSUE TITLE
letter-spacing instead of line-height

### ISSUE THREAD

**Issue by mikestempien** [YumYumNyang/yummy-figma-plugin#7]
Hey, thanks for the plugin, it's very useful. Found a bug tho:
https://github.com/YumYumNyang/yummy-figma-plugin/blob/main/global-style-to-code/src/functions/text.ts#L59
you are assigning letter-spacing to line-height variables here. If you'll find some time to fix that it would be great.

**Comment by YumYumNyang** [comment]
Thank  you for reporting this issue! 
this is huge mistake I made, thank you again for letting me know this
and I published new version of this plugin. check this out :) 
https://www.figma.com/community/plugin/1143791863042221668/global-style-to-code
